# Generated by Django 3.0.2 on 2020-06-09 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '__first__'),
        ('shop', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Mast cheez', max_length=50)),
                ('description', models.TextField(default='This product is cool!')),
                ('actual_price', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('my_price', models.DecimalField(decimal_places=2, default=80, max_digits=10)),
                ('image', models.ImageField(upload_to='products')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.TextField(default='I love this product')),
                ('stock', models.IntegerField(default=0, help_text='Quantity of product you have in stock.Ex: 150')),
                ('approved', models.BooleanField(default=False)),
                ('is_service', models.BooleanField(default=False)),
                ('category', models.ForeignKey(help_text='Category the product belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Category')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Profile')),
                ('shop', models.ForeignKey(help_text='The shop which is going to sell this product.', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
                ('subcategory', models.ForeignKey(help_text='Sub category the product belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.SubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='UUIDTaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_uuidtaggeditem_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_uuidtaggeditem_items', to='taggit.Tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='product.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
