# Generated by Django 3.0.2 on 2020-06-11 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200610_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['user']},
        ),
        migrations.RemoveField(
            model_name='review',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
    ]
